admin_user:
    path:  /lista
    defaults: { _controller: "AdminUserBundle:User:index" }
    requirements: { methods: get }
    
admin_user_buscarpor:
    path:  /lista
    defaults: { _controller: "AdminUserBundle:User:buscarpor" }

admin_user_new:
    path:  /new
    defaults: { _controller: "AdminUserBundle:User:new" }

admin_user_create:
    path:  /create
    defaults: { _controller: "AdminUserBundle:User:create" }
    requirements: { methods: post }

admin_user_edit:
    path:  /{id}/edit
    defaults: { _controller: "AdminUserBundle:User:edit" }

admin_user_update:
    path:  /{id}/update
    defaults: { _controller: "AdminUserBundle:User:update" }
    requirements: { methods: post|put }

admin_user_delete:
    path:  /{id}/delete
    defaults: { _controller: "AdminUserBundle:User:delete" }
    requirements: { methods: post|delete }
