<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EscuelaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscuelaRepository extends EntityRepository
{
    public function findSiglas(){
        $qb = $this->createQueryBuilder('escuela')
                        ->select('escuela.sigla');
        return $this->getArray($qb->getQuery()->getResult());
    }

    public function getArray($values){
        $result = array();
        foreach ($values as $i => $value){
            $result[$value['sigla']] = $value['sigla'];
        }
        return $result;
    }
}
