<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * periodoelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class periodoeRepository extends EntityRepository
{
    public function findAll(): array
    {
        return $this->findBy(array(), array('id' => 'ASC'));
    }

    public function findLastFor(){
        return $this->createQueryBuilder('periodoe')
            ->where('periodoe.peraca < 20000')
            ->setMaxResults(3)
            ->orderBy('periodoe.id', 'DESC');
    }


    public function findLastThree()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT a FROM App:Periodoe a WHERE a.peraca < 20000 ORDER BY a.id DESC');
        $periodos =  $query->setMaxResults(3)->getResult();
        return $this->getArray($periodos);
    }

    public function findLastTenId()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT a.id FROM App:Periodoe a WHERE a.type=:tipo ORDER BY a.id DESC');
        $query->setParameters(array(
            'tipo' => 'p'
        ));
        $result = $query->setMaxResults(10)->getResult();
        return $this->getIds($result);
    }

    public function getArray($values){
        $result = array();
        foreach ($values as $i => $value){
            $result[$value->getObservaciones(). ' de ' .$value->getYear()] = $value->getPeraca();
        }
        return $result;
    }

    public function getIds($values){
        $result = array();
        foreach ($values as $i => $value){
            $result[] = $value['id'];
        }
        return $result;
    }
}
