<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProgramaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramaRepository extends EntityRepository
{
    public function ordenEscuela(){
     $em = $this->getEntityManager();
    // $centros = $em->getRepository('App:Centro')->findAll();
     $query = $em->createQuery('SELECT a FROM AppBundle:Programa a ORDER BY a.escuela ASC');
     $centros = $query->getResult();
     return $centros;
  }

      public function getPorEscuela($escuelaId){
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT a FROM AppBundle:Programa a WHERE a.escuela = :escuelaid')->setParameter('escuelaid', $escuelaId);
        $programas = $query->getResult();
        return $programas;
      }

    public function findByEscuela($escuela){
        return $this->createQueryBuilder('programa')
            ->where('programa.escuela = :escuela')
            ->setParameter('escuela', $escuela)
            ->orderBy('programa.nombre', 'ASC');
    }

    public function getPorIds($ids)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT a FROM AppBundle:Programa a WHERE a.id IN (:ids)')->setParameter('ids', implode(',', $ids));
        $programas = $query->getResult();
        return $programas;
    }

}
