services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $projectDir: '%kernel.project_dir%'

  AppBundle\:
    resource: '../../src/AppBundle/*'
    exclude: '../../src/AppBundle/{DependencyInjection,Entity,Tests}'

  AppBundle\Service\FileUploader:
    arguments:
      $targetDirectory: '%pdfplan_directory%'
