_admin_usuario:
    resource: "@AdminUserBundle/Controller/UserController.php"
    type:     annotation

admin_user_home:
    path:  /home
    defaults: { _controller: "AdminUserBundle:Default:home" }
    
admin_user_send:
    path:  /home/send
    defaults: { _controller: "AdminUserBundle:Default:send" }
    
admin_user_inicio:
    path:  /user/inicio
    defaults: { _controller: "AdminUserBundle:Default:index" }
    
    
admin_user_info:
    path:  /user/info
    defaults: { _controller: "AdminUserBundle:User:info" }   