AdminUserBundle_admin_user:
    resource: "@AdminUserBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user
    
admin_user_info:
    pattern:  /info/user
    defaults: { _controller: "AdminUserBundle:User:info" }
    
admin_user_home:
    pattern:  /home
    defaults: { _controller: "AdminUserBundle:Default:home" }
    
admin_user_send:
    pattern:  /home/send
    defaults: { _controller: "AdminUserBundle:Default:send" }
    
admin_user_inicio:
    pattern:  /unad/inicio
    defaults: { _controller: "AdminUserBundle:Default:index" }
    
unad_user_lista:
    pattern:  /unad/user/lista
    defaults: { _controller: "AdminUserBundle:User:index" }
    requirements: { _method: get }

unad_user_buscarpor:
    pattern:  /unad/user/lista
    defaults: { _controller: "AdminUserBundle:User:buscarpor" }         