_admin_usuario:
    resource: "@AdminUserBundle/Controller/UserController.php"
    type:     annotation

home_user:
    path:  /home
    defaults: { _controller: "AdminUserBundle:Default:home" }
    
home_user_send:
    path:  /home/send
    defaults: { _controller: "AdminUserBundle:Default:send" }
    
home_user_inicio:
    path:  /home/inicio
    defaults: { _controller: "AdminUserBundle:Default:index" }

admin_user_show:
    path:  /unad/user/{id}/doc
    defaults: { _controller: "AdminUserBundle:User:show" }    
    
    
home_user_info:
    path:  /home/info
    defaults: { _controller: "AdminUserBundle:User:info" }   