_escuela_unad:
    resource: "@AdminUnadBundle/Controller/EscuelaController.php"
    type:     annotation
    
_zona_unad:
    resource: "@AdminUnadBundle/Controller/ZonaController.php"
    type:     annotation
    
_centro_unad:
    resource: "@AdminUnadBundle/Controller/CentroController.php"
    type:     annotation        
    
_programa_unad:
    resource: "@AdminUnadBundle/Controller/ProgramaController.php"
    type:     annotation  
    
_docente_unad:
    resource: "@AdminUnadBundle/Controller/DocenteController.php"
    type:     annotation       

_curso_unad:
    resource: "@AdminUnadBundle/Controller/CursoController.php"
    type:     annotation
    
docente_redtutores:
    pattern:  /doc/redtutor
    defaults: { _controller: "AdminUnadBundle:Docente:redtutores" }

docente_coevaltutor:
    pattern:  /doc/coevaltutor
    defaults: { _controller: "AdminUnadBundle:Docente:coevaltutor" }
    
docente_coevalpares:
    pattern:  /doc/coevalpares
    defaults: { _controller: "AdminUnadBundle:Docente:coevalpares" }         