_admin_usuario:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation

home_user:
    path:  /home
    defaults: { _controller: AppBundle\Controller\DefaultController::homeAction }

home_soporte:
    path:  /soporte
    defaults: { _controller: AppBundle\Controller\DefaultController::homeAction }

home_user_send:
    path:  /home/send
    defaults: { _controller: AppBundle\Controller\DefaultController::sendAction }

home_user_inicio:
    path:  /home/inicio
    defaults: { _controller: AppBundle\Controller\DefaultController::indexAction }

home_user_periodo:
    path:  /home/periodo
    defaults: { _controller: AppBundle\Controller\DefaultController::periodAction }

home_user_periodo_select:
    path:  /home/periodo/{id}
    defaults: { _controller: "AppBundle:Default:select" }

admin_user_show:
    path:  /unad/user/{id}/doc
    defaults: { _controller: "AppBundle:User:show" }

admon_user:
    path:  /admon/user
    defaults: { _controller: "AppBundle:User:index" }

home_user_info:
    path:  /home/info
    defaults: { _controller: "AppBundle:User:info" }

home_pass:
    path:  /getpass
    defaults: { _controller: "AppBundle:User:passmed" }

home_pass2:
    path:  /setpass
    defaults: { _controller: "AppBundle:User:setpass" }
    methods: [POST]

#unadbundle

_escuela_unad:
    resource: "@AppBundle/Controller/EscuelaController.php"
    type:     annotation

_zona_unad:
    resource: "@AppBundle/Controller/ZonaController.php"
    type:     annotation

_centro_unad:
    resource: "@AppBundle/Controller/CentroController.php"
    type:     annotation

_programa_unad:
    resource: "@AppBundle/Controller/ProgramaController.php"
    type:     annotation

_docente_unad:
    resource: "@AppBundle/Controller/DocenteController.php"
    type:     annotation

_curso_unad:
    resource: "@AppBundle/Controller/CursoController.php"
    type:     annotation

_lider_unad:
    resource: "@AppBundle/Controller/LiderController.php"
    type:     annotation

_planmejoramiento:
    resource: "@AppBundle/Controller/PlanmejoramientoController.php"
    type:     annotation
_accionespm:
    resource: "@AppBundle/Controller/AccionespmController.php"
    type:     annotation

_redtutores:
    resource: "@AppBundle/Controller/redTutoresController.php"
    type:     annotation

_plangestion:
    resource: "@AppBundle/Controller/PlangestionController.php"
    type:     annotation

_actividadesrol:
    resource: "@AppBundle/Controller/ActividadrolController.php"
    type:     annotation

_rolacedemico:
    resource: "@AppBundle/Controller/RolacademicoController.php"
    type:     annotation

_actividadplang:
    resource: "@AppBundle/Controller/ActividadplangController.php"
    type:     annotation

_rolplang:
    resource: "@AppBundle/Controller/RolplangController.php"
    type:     annotation

_coevaltutor:
    resource: "@AppBundle/Controller/coevalTutorController.php"
    type:     annotation

_coevalpares:
    resource: "@AppBundle/Controller/coevalParesController.php"
    type:     annotation

_coevaldirector:
    resource: "@AppBundle/Controller/coevalDirectorController.php"
    type:     annotation

_coevallider:
    resource: "@AppBundle/Controller/coevalLiderController.php"
    type:     annotation

_avales:
    resource: "@AppBundle/Controller/AvalplangController.php"
    type:     annotation

_archivo:
    resource: "@AppBundle/Controller/ArchivoController.php"
    type:     annotation

_instrumento:
    resource: "@AppBundle/Controller/InstrumentoController.php"
    type:     annotation

_formato:
    resource: "@AppBundle/Controller/formatoPlangController.php"
    type:     annotation

_plangpdf:
    resource: "@AppBundle/Controller/pdfPlangController.php"
    type:     annotation

_base:
    resource: "@AppBundle/Controller/BaseController.php"
    type:     annotation

_consolidar:
    resource: "@AppBundle/Controller/ConsolidarController.php"
    type:     annotation

_hetero:
    resource: "@AppBundle/Controller/HeteroController.php"
    type:     annotation

_dofe:
    resource: "@AppBundle/Controller/DofeController.php"
    type:     annotation

_productividad:
    resource: "@AppBundle/Controller/ProductividadController.php"
    type:     annotation

docente_coevaltutor:
    path:  /doc/coevaltutor
    defaults: { _controller: "AppBundle:Docente:coevaltutor" }

decano_coevallider:
    path:  /dec/coevallider
    defaults: { _controller: "AppBundle:Escuela:coevallider" }


accionespm_editdoc:
    path:  /doc/planm/acc/{id}/edit
    defaults: { _controller: "AppBundle:Accionespm:editdoc" }

planmejoramiento_doc:
    path: /doc/planm/{id}
    defaults: { _controller: "AppBundle:Planmejoramiento:doc" }

plangestion_info:
    path:  /unad/doc/{id}/plan
    defaults: { _controller: "AppBundle:Plangestion:info" }
    methods: GET

plangestion_autoeval:
    path:  /unad/doc/{id}/autoeval
    defaults: { _controller: "AppBundle:Plangestion:autoeval" }
    methods: GET


redtutores_info:
    path:  /unad/doc/{id}/redtutor
    defaults: { _controller: "AppBundle:Docente:redtutoresinfo" }

coeval_info:
    path:  /unad/doc/{id}/coeval
    defaults: { _controller: "AppBundle:Docente:coevalinfo" }

user_info:
    path:  /unad/user/{id}/info
    defaults: { _controller: "AppBundle:User:show" }
