parameters:
  appmed.periodo: '20241'
  appmed.year: '2024'
  appmed.semestre: '20241'
  appmed.periodos:
    - '20231'
    - '20232'
    - '20233'
    - '20234'
    - '20235'
    - '20236'
    - '20237'
    - '20241'

services:
#    admin_user.example:
#        class: %admin_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
