<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * evalDofeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class evalDofeRepository extends EntityRepository
{


    public function getActividades($eval)
    {
        $connection = $this->getEntityManager()->getConnection();
        $q = "SELECT red.id, ac.actividad_id FROM red_dofe AS red
              JOIN actividad_plang AS ac ON red.docente_id = ac.plan_id
              WHERE red.id = " . $eval . " AND ac.autoevaluacion != 0";
        $stmt = $connection->executeQuery($q);
        return $stmt->fetchAllAssociative();
    }
}
