<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InstrumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstrumentoRepository extends EntityRepository
{
}
