_planmejoramiento:
    resource: "@AdminMedBundle/Controller/PlanmejoramientoController.php"
    type:     annotation
_accionespm:
    resource: "@AdminMedBundle/Controller/AccionespmController.php"
    type:     annotation

_redtutores:
    resource: "@AdminMedBundle/Controller/redTutoresController.php"
    type:     annotation
    
_plangestion:
    resource: "@AdminMedBundle/Controller/PlangestionController.php"
    type:     annotation
    
_actividadesrol:
    resource: "@AdminMedBundle/Controller/ActividadrolController.php"
    type:     annotation   

_rolacedemico:
    resource: "@AdminMedBundle/Controller/RolacademicoController.php"
    type:     annotation       

_actividadplang:
    resource: "@AdminMedBundle/Controller/ActividadplangController.php"
    type:     annotation    
    
_coevaltutor:
    resource: "@AdminMedBundle/Controller/coevalTutorController.php"
    type:     annotation        

_coevalpares:
    resource: "@AdminMedBundle/Controller/coevalParesController.php"
    type:     annotation     
    
accionespm_editdoc:
    pattern:  /doc/planm/acc/{id}/edit
    defaults: { _controller: "AdminMedBundle:Accionespm:editdoc" }
    
planmejoramiento_doc:
    pattern: /doc/planm/{id}
    defaults: { _controller: "AdminMedBundle:Planmejoramiento:doc" }
 
plangestion_info:
    pattern:  /unad/doc/{id}/plan
    defaults: { _controller: "AdminMedBundle:Plangestion:info" }

plangestion_autoeval:
    pattern:  /unad/doc/{id}/autoeval
    defaults: { _controller: "AdminMedBundle:Plangestion:autoeval" }  
    
redtutores_info:
    pattern:  /unad/doc/{id}/redtutor
    defaults: { _controller: "AdminUnadBundle:Docente:redtutoresinfo" }      
    